### ISSUE TITLE
node_modules shoudn't be committed

### ISSUE THREAD

**Issue by adripo** [sudo-bot/action-pull-request-merge#11]
Hi, I just noticed that node_modules folder is versioned inside this repository and the dependencies inside that folder are not listed in package.json.

Is there a reason for such behaviour or can you convert the project with the correct approach?

Thanks

**Comment by williamdes** [comment]
Hi 
Are you familiar with github actions?

**Comment by adripo** [comment]
I just started to learn them recently, but I am happy to help out if needed.

**Comment by williamdes** [comment]
> I just started to learn them recently, but I am happy to help out if needed.

Thank you, I think there is no need for maintenance here, maybe you could give a hand at @phpMyAdmin ?

**Comment by williamdes** [comment]
> node_modules shoudn't be committed

They should

See : https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

From your terminal, commit your action.yml, index.js, **node_modules**, package.json, package-lock.json, and README.md files. **If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.**

**Comment by adripo** [comment]
Okay, sorry for opening the issue then. I will study more how actions work.

**Comment by williamdes** [comment]
> Okay, sorry for opening the issue then. I will study more how actions work.

You can have a look at how I built my very simple actions at @sudo-bot 
Some other devs have done better and more complex ones

**Comment by williamdes** [comment]
[Version 2](https://github.com/sudo-bot/action-pull-request-merge/releases/tag/v2) is out!
